#!fichero makefuile
#complirar com: $make
#

main:
	@echo	"\n=== Uso: crear o eliminar\n"
	
	
crear:
	@echo	"\n=== Uso: crear...\n"
	mkdir curso2
	mkdir curso3
	@echo	"Carpetas creadas"
	tree

	
eliminar:
	@echo	"\n=== Uso: eliminar...\n"
	rm -rf curso*
	@echo	"Carpetas eliminadas"
